package com.example.thomas.voyage.ResClasses;


public class ConstRes {

    public final int
            TOTAL_ITEMS_PLAYER_LV1 = 50,
            TOTAL_ITEMS_MERCHANT_LV1 = 20,
            TOTAL_HEROES_MERCHANT = 3,
            TOTAL_HEROES_PLAYER = 10,
            COSTS_TO_HEAL_PER_HP = 100;

    public final String
            IS_FIRST_RUN = "IS_FIRST_RUN",
            QUICK_COMBAT_FIRST_STARTED = "QUICK_COMBAT_FIRST_STARTED",
            NOT_USED = "NOT_USED",
            ORIGIN = "ORIGIN",
            MERCHANT_SLAVE_ID = "MERCHANT_SLAVE_ID",
            HERO_DATABASE_INDEX = "HERO_DATABASE_INDEX",
            MONSTER_NAME = "MONSTER_NAME",
            MONSTER_DESCRIPTION = "MONSTER_DESCRIPTION",
            MONSTER_CHECKOUT = "MONSTER_CHECKOUT",
            MONSTER_IMG_RES = "MONSTER_IMG_RES",
            MONSTER_HITPOINTS_NOW = "MONSTER_HITPOINTS",
            MONSTER_HITPOINTS_TOTAL = "MONSTER_HP_TOTAL",
            MONSTER_DAMAGE_MIN = "MONSTER_DMG_MIN",
            MONSTER_DAMAGE_MAX = "MONSTER_DMG_MAX",
            MONSTER_BLOCK = "MONSTER_BLOCK",
            MONSTER_EVASION = "MONSTER_EVASION",
            MONSTER_ACCURACY = "MONSTER_ACC",
            MONSTER_CRIT_CHANCE = "MONSTER_CRIT_CHANCE",
            MONSTER_CRIT_MULTIPLIER = "MONSTER_CRIT_MULTIPLIER",
            MONSTER_RESISTANCE = "MONSTER_RESISTANCE",
            MONSTER_DIFFICULTY = "MONSTER_DIFFICULTY",
            MONSTER_BOUNTY = "MONSTER_BOUNTY",
            CURRENT_BIOME = "CURRENT_BIOME",
            POINTS_TO_TRANSFER = "POINTS_TO_TRANSFER",
            MY_POCKET = "currentMoneyLong",
            SLOT_INDEX = "SLOT_INDEX",
            COMBAT_LEVEL_OF_MONSTERS = "COMBAT_LEVEL_OF_MONSTERS",
            COMBAT_LENGTH = "COMBAT_LENGTH",
            COMBAT_MONSTER_COUNTER = "COMBAT_MONSTER_COUNTER",
            COMBAT_BOUNTY_TOTAL = "COMBAT_BOUNTY_TOTAL",
            SP_CURRENT_MONEY_PREF = "CURRENT_MONEY_PREF",
            SP_SLAVE_MERCHANT = "SP_SLAVE_MERCHANT",
            SP_TOTAL_HEROES_MERCHANT = "TOTAL_HEROES_MERCHANT_PREF";
}
